### ISSUE TITLE
http: proxy error: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by yuriydzobak** [kyverno/policy-reporter-ui#159]
Hi, 
you have fixe issue `Fix API Proxy for APIs behind ReverseProxy (like NGINX Ingress)` in release `2.11.1`
I'm using ssl and when it's tring to reach https i got issue
```
2022/08/17 16:25:49 http: proxy error: x509: certificate signed by unknown authority
2022/08/17 16:25:49 http: proxy error: x509: certificate signed by unknown authority
2022/08/17 16:25:49 http: proxy error: x509: certificate signed by unknown authority
2022/08/17 16:25:49 http: proxy error: x509: certificate signed by unknown authority
2022/08/17 16:25:49 http: proxy error: x509: certificate signed by unknown authority
2022/08/17 16:25:49 http: proxy error: x509: certificate signed by unknown authority
2022/08/17 16:25:49 http: proxy error: x509: certificate signed by unknown authority
2022/08/17 16:25:49 http: proxy error: x509: certificate signed by unknown authority
2022/08/17 16:25:49 http: proxy error: x509: certificate signed by unknown authority
2022/08/17 16:25:49 http: proxy error: x509: certificate signed by unknown authority
2022/08/17 16:25:49 http: proxy error: x509: certificate signed by unknown authority
2022/08/17 16:25:49 http: proxy error: x509: certificate signed by unknown authority
2022/08/17 16:25:50 http: proxy error: x509: certificate signed by unknown authority
2022/08/17 16:25:50 http: proxy error: x509: certificate signed by unknown authority
```
Could you download public cert or skip verification ssl?
Thanks

**Comment by fjogeleit** [comment]
Thanks for reporting, I released v1.6.2 with the missing certs.

You can try it with:

```yaml
ui:
  image:
    tag: 1.6.2
```

**Comment by fjogeleit** [comment]
I close the issue for now, let me know if you still encounter any issues. I will release a new Helm Chart version with the fixed version in the beginning of the next week.

**Comment by yuriydzobak** [comment]
I've checked it works.
Thanks

**Comment by phccdk** [comment]
Hi, is it possible to skip also?

**Comment by fjogeleit** [comment]
Hey, what do you want to skip exactly?

**Comment by phccdk** [comment]
Sorry for missing the context.

I'm inserting external clusters to be able to see them from one UI - but as we run our own CA internally the request to the policy-api fail because it can't trust the CA.

So it could be nice to have this call skipTLS or provide the CA to trust somehow.

**Comment by fjogeleit** [comment]
okay, I will check this.

**Comment by fjogeleit** [comment]
I added support for both, skipTLS or configure a path to the custom CA.

I will add this options to the Helm Chart and the possibility to add volumes to the UI deployment, so you can mount your custom CA and use it or skipTLS.
