### ISSUE TITLE
Time in policy UI

### ISSUE THREAD

**Issue by yuriydzobak** [kyverno/policy-reporter-ui#160]
Hi,
When feature enabled
```
    kyvernoPlugin:
      enabled: true
      blockReports:
        enabled: true
        eventNamespace: default
        results:
          maxPerReport: 200
          keepOnlyLatest: false
```          
Would be nice if policy report displays time when it happened. For example, someone tried to create something in cluster and we can identity which time it was
<img width="1379" alt="image" src="https://user-images.githubusercontent.com/70581130/185599328-84cea4e5-4424-4140-b094-2465ebe665b9.png">
The timestamp exists in `policyreports`
```
apiVersion: wgpolicyk8s.io/v1alpha2
kind: PolicyReport
metadata:
  creationTimestamp: "2022-08-19T01:15:13Z"
  generation: 3
  labels:
    managed-by: policy-reporter-kyverno-plugin
  name: polr-ns-infra-blocked
  namespace: infra
  resourceVersion: "425846096"
  uid: ac8d1db4-628a-4494-bac0-9500a5294e67
results:
- category: Best Practices
  message: An image tag is required.
  policy: disallow-latest-tag
  properties:
    eventName: disallow-latest-tag.170c9a02a43f46c4
    resultID: 45728f2981ddc9dd20141aeede8957c187147464
  resources:
  - kind: Pod
    name: my-nginx
    namespace: infra
  result: fail
  rule: require-image-tag
  source: Kyverno Event
  timestamp:
    nanos: 0
    seconds: 1660871713
summary:
  error: 0
  fail: 1
  pass: 0
  skip: 0
  warn: 0
```

**Comment by fjogeleit** [comment]
thanks for the request, would it be enough when I add the created time as property? So it is displayed like eventName. Would you prefer a timestamp or a timeformat like YYYY-MM-DD HH:mm:ss

**Comment by yuriydzobak** [comment]
> thanks for the request, would it be enough when I add the created time as property? So it is displayed like eventName. Would you prefer a timestamp or a timeformat like YYYY-MM-DD HH:mm:ss

Thanks for fast replay
Yes it's enough

**Comment by fjogeleit** [comment]
with version `1.4.1` I addd the `time` property to the results.

**Comment by fjogeleit** [comment]
I will release all the new versions in the end of next week.
