### ISSUE TITLE
Filter view issue

### ISSUE THREAD

**Issue by yuriydzobak** [kyverno/policy-reporter-ui#161]
HI,
When you selected view by `Group Results by Policy` or `Group Results by Category` and didn't select any `category` or `policy` that displays empty
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/70581130/185601074-e6780759-51f9-4eef-bb12-1f7d7bf093a7.png">
<img width="1705" alt="image" src="https://user-images.githubusercontent.com/70581130/185601107-24da87f3-03ef-412b-99a0-dd731a67258a.png">

When you selected any `policy` or `catagory` then it works
<img width="1708" alt="image" src="https://user-images.githubusercontent.com/70581130/185601286-bf76b873-cfc9-46d2-b282-64ce2782306a.png">

Seems, you don't send `all` into query

**Comment by fjogeleit** [comment]
Thanks I will check it.

**Comment by fjogeleit** [comment]
I fixed it with the release v1.6.3, so you can try it when the build is done with the image.tag `1.6.3`

**Comment by yuriydzobak** [comment]
> I fixed it with the release v1.6.3, so you can try it when the build is done with the image.tag `1.6.3`

Thanks, it works as expected
