### ISSUE TITLE
Cluster view option

### ISSUE THREAD

**Issue by yuriydzobak** [kyverno/policy-reporter-ui#164]
Hi,
If you attached a new clusters into policy-report-ui it displays label `default`
<img width="587" alt="image" src="https://user-images.githubusercontent.com/70581130/186635000-21020b14-8a8d-44ba-ad5a-073a6c35fe99.png">

would be nice if UI has option to hide `default` cluster or `rename` because if you have 10 cluster and you see `default` that confuse what cluster is

**Comment by fjogeleit** [comment]
hey thanks for your request, I will check it out. I think a configuration for a custom name should be not hard to implement.

**Comment by fjogeleit** [comment]
I will release the new helm version with the new `ui.clusterName` configuration today with the other recent changes.
