### ISSUE TITLE
Supporting k8s labels as filters

### ISSUE THREAD

**Issue by sherifkayad** [kyverno/policy-reporter-ui#191]
I think adding a filter to accept a key / value pairs based on a kubernetes label and its value to the PolicyReports and ClusterPolicyReports might be a good feature.

Our desired use case is to enable e.g. filtering issues by teams or by applications assuming we have an `owner` and an `app` labels on the report objects.

What do you think?

**Comment by fjogeleit** [comment]
Related to https://github.com/kyverno/policy-reporter/pull/230

The UI implementation would look like:

Configuration:

```yaml
labelFilter: ["app", "owner"]
```
<img width="1782" alt="Bildschirmfoto 2022-12-02 um 14 22 43" src="https://user-images.githubusercontent.com/16627596/205302958-0eacd2a9-0fdf-44b2-a46f-4772bf8a1cb8.png">

**Comment by sherifkayad** [comment]
@fjogeleit any news on the next release date?

**Comment by fjogeleit** [comment]
Hey, sorry for the delay. I finalize another feature. So it will be in the next two days
