### ISSUE TITLE
The results displayed are different when the search is successful and when the search is not successful

### ISSUE THREAD

**Issue by fengshunli** [kyverno/policy-reporter-ui#211]
Kind search is not supported, and it cannot be searched, and the displayed result columns are reduced
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/18587688/212520189-7aa0a981-fb9e-423c-aa7b-7078926ee054.png">

default display
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/18587688/212520267-12876510-be40-406c-8582-fb793ef08433.png">

**Comment by fjogeleit** [comment]
Released with Helm Chart Version 2.15.0
