### ISSUE TITLE
Forgotten about annotations in template file in helm

### ISSUE THREAD

**Issue by Asgoret** [kyverno/policy-reporter-ui#327]
There is no such thins as metadata.annotations in policy-reporter-ui in helm chart) But such thing exists in values.yaml
![image](https://github.com/kyverno/policy-reporter-ui/assets/30697011/933e9f0f-7f84-40dc-9559-625f58ba9e24)

**Comment by fjogeleit** [comment]
Thanks for mentioning, I’ll have a look

**Comment by fjogeleit** [comment]
Fix released with Helm Chart Version `2.21.5`
