### ISSUE TITLE
line breaks in validation messages

### ISSUE THREAD

**Issue by oocx** [kyverno/policy-reporter-ui#328]
Hi,

I discovered policy-reporter today think it's an amazing tool, thanks! :)

In my rules, I have messages that contain line breaks to make the message more readable. For example:
```
      message: >-
        the ingress object {{request.object.metadata.name}} contains the following annotations:
        {{request.object.metadata.annotations.keys(@)[?contains(@, 'nginx.ingress.kubernetes.io/')] | join(', ', @) }}

        allowed annotations:
        nginx.ingress.kubernetes.io/rewrite-target
        nginx.ingress.kubernetes.io/proxy-body-size
        nginx.ingress.kubernetes.io/configuration-snippet
        nginx.ingress.kubernetes.io/auth-realm
        ...
```

In Policy Reporter UI, the line breaks are not rendered so that everything is shown as a single large line of text.

Could you please add support for line breaks in the UI?

Thanks
Mathias

**Comment by fjogeleit** [comment]
Hey thanks for your feedback and reporting, I’ll take a look on it.

**Comment by fjogeleit** [comment]
Should be fixed with the latest release
