### ISSUE TITLE
Feature: Show `PolicyExceptions` in `policy-reporter-ui `under kyverno-plugin.

### ISSUE THREAD

**Issue by ranjit-se7en** [kyverno/policy-reporter-ui#378]
We have a ClusterPolicy for `disallow-capabalities` and we have added a `PolicyException` to exclude Pods which have the `linkerd` init containers.

While browsing through the policy-reporter-ui, it occurred that we should also list this `PolicyException` which is attached to the `ClusterPolicy`, and list the resources skipped by the `PolicyException`.

Under the `kyverno-plugin` of the policy-reporter-ui dashboard we can see the `Failing Policy Results`, `Passing Policy Results`, similarly we could have a section that shows the PolicyException attached to this policy and the `Skipped Policy Results` which were skipped by the exception.

<img width="1727" alt="image" src="https://github.com/kyverno/policy-reporter-ui/assets/40806366/01d20d88-6768-4caa-82b3-b9621f3b7e89">

**Comment by fjogeleit** [comment]
the next beta release of Policy Reporter UI v2 includes a new Kyverno Plugin which provides a list of related Policy Exception of a given Policy

<img width="1408" alt="Bildschirmfoto 2024-09-01 um 11 34 05" src="https://github.com/user-attachments/assets/88613547-0ab9-4ed1-9fb8-f1b45c88ff53">

**Comment by ranjit-se7en** [comment]
> the next beta release of Policy Reporter UI v2 includes a new Kyverno Plugin which provides a list of related Policy Exception of a given Policy
> 
> <img alt="Bildschirmfoto 2024-09-01 um 11 34 05" width="1408" src="https://private-user-images.githubusercontent.com/16627596/363480593-88613547-0ab9-4ed1-9fb8-f1b45c88ff53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2OTMxMTksIm5iZiI6MTcyNTY5MjgxOSwicGF0aCI6Ii8xNjYyNzU5Ni8zNjM0ODA1OTMtODg2MTM1NDctMGFiOS00ZWQxLTlmYjgtZjFiNDVjODhmZjUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDA3MDY1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzOTAzMmI5ZGExNDA5MzYyZTEwNjM4ZWFkYzM4OGI3ODVhOWRkYzczMDU5YmE3OTFmOTk1ODlmOTE3YzU4ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QrNYya6Nojykqj8PsVnompyDZwjiawcz27fkWGOCenM">

Does it also show resources that are skipped by the policyException?

**Comment by fjogeleit** [comment]
Yes, the view has a table with all resources and related status, so you see the entry for the skipped item
