### ISSUE TITLE
Resources that do not exists anymore in "Kyverno Events" tab

### ISSUE THREAD

**Issue by Pilotindream** [kyverno/policy-reporter-ui#400]
Hello Community,

In my Policy Reporter UI in "Kyverno Events" tab I am able to see resources the do not exist anymore in my cluster:

![image](https://github.com/user-attachments/assets/b5f0d5e1-9cc0-4db0-9f4b-804520cfd809)

I thought that here will be visible only resources that currently exists in the cluster?
In "Kyverno" tab I see only resources that currently exists in the cluster, which I think is ok.

So I am wondering whether it is expected behavior?

Thanks in advance!

**Comment by fjogeleit** [comment]
PolicyReports with "Kyverno Events" are created by the Kyverno Plugin based on Keubernetes Events from rejected admission requests from Kverno Enforce Policies. If you try to create a resource but it is rejected the actual resources never existed.

This reports are a log of rejected admission requests rather then a status about existing resources. This is only the case for PolicyReports with the "Kyverno" source.
