### ISSUE TITLE
match colors of bar graphs with status in policy-reports view + add Pie chart for showing ratio

### ISSUE THREAD

**Issue by Issif** [kyverno/policy-reporter-ui#8]
I propose to set green/red as colors for bar charts in policy-reports view. It allows detect which one is quickly

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/4520100/129767644-b143182c-4393-455d-9cdf-e3033317f33d.png">

A pie chart would be useful too for allowing to check ratio between pass/fail reports.

**Comment by fjogeleit** [comment]
With v1.4.0 I added colors to the different Status Charts
<img width="1503" alt="Bildschirmfoto 2021-08-20 um 10 57 06" src="https://user-images.githubusercontent.com/16627596/130208594-e44a0a72-6535-49ea-b410-876c7849865f.png">

Do you mean a PieChart per Namespace? That could be unconfident for many namespaces

**Comment by Issif** [comment]
A pie chart per Status (fail/pass).

Thank you for colors, I like that 👍

**Comment by fjogeleit** [comment]
<img width="1450" alt="Bildschirmfoto 2024-03-24 um 14 21 06" src="https://github.com/kyverno/policy-reporter-ui/assets/16627596/dd24b670-0a81-4d74-830f-1c77c59c92ab">

finally done in UI v2.x 😄
